name: Fullstack CI - React & Node.js (No frontend folder)

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # FRONTEND at root
      - name: Install frontend dependencies
        run: npm install

      - name: Build React app
        run: npm run build

      # BACKEND
      - name: Install backend dependencies
        working-directory: backend
        run: npm install
